# Este arquivo é parte do projeto "Cypress End-to-End Tests".
# Este arquivo contém a configuração do GitHub Actions para executar testes end-to-end com Cypress.
# 


name: End-to-end tests 
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # aqui ele faz o checkout do código do repositório adicionando no workspace do GitHub Actions
      - name: Cypress run
        uses: cypress-io/github-action@v6 # aqui ele executa o Cypress usando a ação oficial do Cypress no GitHub Actions para rodar os testes end-to-end
